// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5rpBujykHTTll6EQj9-7pXECqxbHCExw',
    appId: '1:724687478514:web:4cee16d706676035043a6b',
    messagingSenderId: '724687478514',
    projectId: 'turfapp-1fc7f',
    authDomain: 'turfapp-1fc7f.firebaseapp.com',
    storageBucket: 'turfapp-1fc7f.firebasestorage.app',
    measurementId: 'G-EFRR0D4777',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnMiXOArvxPOiOz5FZRS2UyZCvR36WT1s',
    appId: '1:724687478514:android:f81479cf092fe1bc043a6b',
    messagingSenderId: '724687478514',
    projectId: 'turfapp-1fc7f',
    storageBucket: 'turfapp-1fc7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxsYhcYLql1J_nIv7qoqO7cLCaZZPS8Pg',
    appId: '1:724687478514:ios:2f47f8fcfe2302f0043a6b',
    messagingSenderId: '724687478514',
    projectId: 'turfapp-1fc7f',
    storageBucket: 'turfapp-1fc7f.firebasestorage.app',
    iosBundleId: 'com.example.playnation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxsYhcYLql1J_nIv7qoqO7cLCaZZPS8Pg',
    appId: '1:724687478514:ios:2f47f8fcfe2302f0043a6b',
    messagingSenderId: '724687478514',
    projectId: 'turfapp-1fc7f',
    storageBucket: 'turfapp-1fc7f.firebasestorage.app',
    iosBundleId: 'com.example.playnation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5rpBujykHTTll6EQj9-7pXECqxbHCExw',
    appId: '1:724687478514:web:5df5dd024b768c1d043a6b',
    messagingSenderId: '724687478514',
    projectId: 'turfapp-1fc7f',
    authDomain: 'turfapp-1fc7f.firebaseapp.com',
    storageBucket: 'turfapp-1fc7f.firebasestorage.app',
    measurementId: 'G-QN92WRQZSV',
  );
}
